### ISSUE TITLE
About the patch correctness assessment of SimFix-Math-98

### ISSUE THREAD

**Issue by DehengYang** [thwak/confix2019result#1]
Dear @thwak ,

Thank you very much for revisiting the patch correctness assessment of previous patches generated by other APR tools like SimFix, CapGen. This is quite meaningful and insightful to the community!

Here I would like to ask for your help with your patch correctness assessment of SimFix (see https://github.com/thwak/confix2019result/blob/master/patches/assessment-others.md#simfix-8):

> Human patch fixed two files BigMatrixImpl.java and RealMatrixImpl.java.
> SimFix generated two patches, each of them fixes one of the two files only.
> Hence SimFix patch is partial and incorrect.

I noticed that the SimFix patch for Math 98 (https://github.com/xgdsmileboy/SimFix/tree/master/final/result/patch/math/98) spans two files and consists of two chunks of code changes, which is identical to the associated human-developer patch provided by Defects4J. Therefore, seemingly this APR-generated patch is correct. 

So it would be sincerely appreciated if any further explanation could be provided for your judgment on this APR-generated patch. Thank you!

Yours sincerely,
Deheng

**Comment by thwak** [comment]
It was long time ago, so I'm not 100% sure about the decision until I dig up some old data from backup drives, 

but if I remember correctly, SimFix patch for math-98 was considered partial since those two fixed files were actually separate.

Human-written patch was fixing two files in one version. SimFix can fix either file, but cannot fix both at once.
I think the number in front of the class name - e.g., 0_XXX.java, 1_XXX.java - was about different attempts or trials of patch generation.

**Comment by DehengYang** [comment]
Dear @thwak ,

Thank you very much for the prompt reply! That perfectly solves my doubts.

Yours sincerely,
Deheng
